language: python
sudo: false

deploy:
  provider: pypi
  user: __token__
  password: pypi-AgEIcHlwaS5vcmcCJGI3MjJmMGMwLWFiOGItNDM0OC1hNDU4LTMzMGNlOGNiZDFjNgACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgbgpZWcaPhkAeEq5UXSLzmZ4Y92Ljh9qz0uQrFy-YcFA
  on:
    tags: true
    repo: christianfrech/quantropypro


python:
  - '3.6'


install:
- travis_retry pip install -r requirements-dev.txt
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
- flake8 --ignore N802,N806 `find . -name \*.py | grep -v setup.py | grep -v version.py | grep -v __init__.py | grep -v /doc/`
- mkdir for_test
- cd for_test
- py.test --pyargs quantropypro --cov-report term-missing --cov=quantropypro

after_success:
- coveralls
